#### Зависимость векторов

In [1]:
import numpy as np

In [3]:
e1 = np.array([1., 0., 0.])
e2 = np.array([0., 5., 0.])

In [4]:
5*e1+3*e2

array([  5.,  15.,   0.])

In [5]:
a = np.array([-3., 10., 0.])

In [6]:
3*e1 - 2*e2 + 1*a

array([ 0.,  0.,  0.])

In [7]:
m = np.array([e1,e2,a])

In [9]:
m

array([[  1.,   0.,   0.],
       [  0.,   5.,   0.],
       [ -3.,  10.,   0.]])

#### Вектора объединены в матрицу. Посчитаем ранг:

In [10]:
np.linalg.matrix_rank(m)

2