In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
b = np.array([1,2,3])

In [4]:
a*10

array([10, 20, 30])

In [5]:
np.dot(a,b)

14

In [16]:
a = np.random.randint(1, 100, (4,5))

In [17]:
a

array([[12,  5, 61, 49, 18],
       [ 4, 53, 53, 63,  1],
       [23, 86, 91, 68, 36],
       [45, 55, 72,  3, 29]])

In [34]:
b = np.random.randint(0, 6,(5))
b

array([2, 0, 4, 4, 3])

In [36]:
c = np.dot(a,b)

In [37]:
c

array([518, 475, 790, 477])

In [1]:
с

NameError: name 'с' is not defined